# Chapter 1. 신경망복습
## 수학과 파이썬 복습

In [1]:
# 벡터와 행렬
import numpy as np

x = np.array([1,2,3])
x.__class__ # 클래스 이름 표기

numpy.ndarray

In [2]:
x.shape

(3,)

In [6]:
x.ndim #1차원 배열이고 원소 수 3개인 벡터

1

In [7]:
W = np.array([[1,2,3],[4,5,6]])

In [8]:
W.shape

(2, 3)

In [9]:
W.ndim

2

In [11]:
#행렬의 원소별(element-wise) 연산
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
# 브로드캐스트
A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [15]:
b = np.array([10,20])
A*b

array([[10, 40],
       [30, 80]])

In [17]:
# 벡터의 내적과 행렬의 곱
#벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [18]:
#행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

* 물론 둘다 np.dot() 가능하나 코드 상 분리해주어 의도를 명확히 하라!
* 행렬 형상 확인도 중요하다.

## 신경망의 추론
### 신경망 추론 전체 그림

In [20]:
# 완전연결계층에 의한 변환 미니배치 버전
import numpy as np
W1 = np.random.randn(2,4) #가중치
b1 = np.random.randn(4) # 편향
x = np.random.randn(10,2) # 입력
h = np.matmul(x, W1) + b1
# 이를 비선형 효과 부여하는 것이 시그모이드입니다.

In [21]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [22]:
a = sigmoid(h)